"""Recover known parameters from profiles generated by the forward model.

Compares profile scale conventions and noise normalisations.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import yaml

from span_editor.fitting import LEAST_SQUARES_SCALE, SCALES, fit_parameters
from span_editor.io import load_assigned_inputs
from span_editor.model import SpanModel
from span_editor.occupancy import (
    ModelParameters,
    Profile,
    capture_probability_curve,
    link_alpha_for_index,
    saturation_index,
)
from span_editor.synthetic import synthetic_corpus
from span_editor.tether import TetherSampler

# Increase in a sum of squared residuals that marks the edge of a profile
# likelihood interval for one parameter, in units of the residual variance.
# These are the chi-squared quantiles on one degree of freedom.
CHI2_ONE_DF = {0.68: 0.989, 0.95: 3.841}


def add_noise(
    profile: Profile, sigma: float, rng: np.random.Generator, normalisation: str = "observed"
) -> Profile:
    """Additive noise on the normalised profile, matched to replicate dispersion.

    The two normalisations differ in whether the noisy profile is divided by its
    own peak. Dividing by it is what curating a window from a published figure
    amounts to, and it is biased: the peak is one order statistic and noise
    inflates it. Leaving the generating peak in place matches what the fit
    assumes, so comparing the two isolates how much of any recovery error comes
    from that step alone.
    """
    normalised = profile.normalised()
    noisy = normalised.values + rng.normal(0.0, sigma, size=normalised.values.shape)
    noisy = np.clip(noisy, 0.0, None)
    if noisy.max() <= 0:
        noisy = normalised.values.copy()
    if normalisation == "observed":
        noisy = noisy / noisy.max()
    return Profile(indices=normalised.indices, values=noisy)


def peak_occupancy(model: SpanModel, contexts, radius: float, persistence: float) -> float:
    """Largest capture probability over the corpus at the reference radius."""
    peak = 0.0
    for context in contexts:
        tether = model.sampler.sample(
            linker=context.entry.linker,
            effector=context.effector,
            anchor=context.anchor,
            occupancy=context.occupancy,
            structure_id=context.entry.structure_id or "none",
        )
        _, curve = capture_probability_curve(
            tether, context.substrate(persistence), np.array([radius]), indices=context.indices
        )
        peak = max(peak, float(curve.max()))
    return peak


def profile_interval(
    indices: np.ndarray, losses: np.ndarray, variance: float, level: float
) -> tuple[float, float]:
    """Range of the saturation index whose loss stays within the threshold."""
    threshold = losses.min() + CHI2_ONE_DF[level] * variance
    inside = indices[losses <= threshold]
    if inside.size == 0:
        best = indices[int(np.argmin(losses))]
        return float(best), float(best)
    return float(inside.min()), float(inside.max())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assigned", type=Path, default=Path("configs/assigned_inputs.yaml"))
    parser.add_argument("--params", type=Path, default=Path("configs/params.yaml"))
    parser.add_argument("--effector", default="apobec1")
    parser.add_argument("--capture-radius", type=float, default=9.0)
    parser.add_argument("--ssdna-persistence", type=float, default=14.0)
    parser.add_argument("--saturation-index", type=float, default=3.0)
    parser.add_argument("--index-min", type=float, default=0.05)
    parser.add_argument("--index-max", type=float, default=60.0)
    parser.add_argument("--index-steps", type=int, default=15)
    parser.add_argument("--noise", type=float, default=0.08)
    parser.add_argument(
        "--noise-normalisation", choices=["observed", "generating"], default="observed"
    )
    parser.add_argument("--scale", choices=SCALES, default=LEAST_SQUARES_SCALE)
    parser.add_argument("--tether-chains", type=int, default=4000)
    parser.add_argument("--substrate-samples", type=int, default=600)
    parser.add_argument("--seed", type=int, default=20260101)
    parser.add_argument("--jobs", type=int, default=1, help="processes to spread the grid over")
    parser.add_argument("--quick", action="store_true", help="small grids, for a smoke run")
    parser.add_argument("--out", type=Path, default=Path("results/synthetic_recovery.json"))
    args = parser.parse_args(argv)

    assigned = load_assigned_inputs(args.assigned)
    settings = yaml.safe_load(args.params.read_text(encoding="utf-8"))
    reference_radius = float(settings["link"]["reference_radius"])

    effector = assigned.effectors[args.effector]
    sampler = TetherSampler(
        compositions=assigned.compositions, n_chains=args.tether_chains, seed=args.seed
    )
    model = SpanModel(sampler)

    lengths = (8, 24) if args.quick else (8, 16, 24, 32)
    standoffs = (22.0,) if args.quick else (20.0, 26.0)
    curvatures = (0.0,) if args.quick else (0.0, 0.12)
    contexts = synthetic_corpus(
        effector=effector,
        linker_lengths=lengths,
        standoffs=standoffs,
        curvatures=curvatures,
        n_samples=args.substrate_samples,
        seed=args.seed,
    )

    scale = peak_occupancy(model, contexts, reference_radius, args.ssdna_persistence)
    if scale <= 0:
        raise RuntimeError("no capture at the reference radius; check the synthetic geometry")

    truth = ModelParameters(
        capture_radius=args.capture_radius,
        ssdna_persistence=args.ssdna_persistence,
        link_alpha=link_alpha_for_index(args.saturation_index, scale),
    )

    rng = np.random.default_rng(args.seed)
    true_modes = []
    for context in contexts:
        generated = model.predict(context, truth)
        true_modes.append(generated.mode)
        context.entry.observed = add_noise(
            generated, args.noise, rng, args.noise_normalisation
        )

    if args.quick:
        radii = np.array([7.0, 9.0, 11.0])
        persistences = np.array([10.0, 14.0, 20.0])
        indices = np.array([0.3, 3.0, 30.0])
    else:
        radii = np.arange(5.0, 15.1, 1.0)
        persistences = np.array([8.0, 10.0, 12.0, 14.0, 17.0, 20.0, 25.0])
        indices = np.logspace(
            np.log10(args.index_min), np.log10(args.index_max), args.index_steps
        )
    alphas = np.asarray([link_alpha_for_index(index, scale) for index in indices])

    result = fit_parameters(
        model, contexts, radii, persistences, alphas, n_jobs=args.jobs, scale=args.scale
    )
    recovered = result.parameters
    recovered_index = saturation_index(recovered.link_alpha, scale)
    on_edge = bool(
        np.isclose(recovered.link_alpha, alphas.min())
        or np.isclose(recovered.link_alpha, alphas.max())
    )

    # Profile the loss over the saturation index, minimising over the other two
    # parameters at each value. Residual variance is estimated from the fit
    # rather than assumed from the noise that was injected.
    profile = result.surface.min(axis=(0, 1))
    n_residuals = sum(
        int(np.isin(np.asarray(c.indices), c.entry.observed.indices).sum())
        for c in contexts
        if c.entry.observed is not None
    )
    degrees_of_freedom = max(n_residuals - 3, 1)
    variance = float(profile.min()) / degrees_of_freedom
    interval_68 = profile_interval(indices, profile, variance, 0.68)
    interval_95 = profile_interval(indices, profile, variance, 0.95)
    grid_ratio = float(indices[1] / indices[0]) if indices.size > 1 else 1.0
    steps_95 = (
        float(np.log(interval_95[1] / interval_95[0]) / np.log(grid_ratio))
        if interval_95[0] > 0 and grid_ratio > 1
        else 0.0
    )

    offsets = np.asarray(
        [
            model.predict(context, recovered).mode - true_mode
            for context, true_mode in zip(contexts, true_modes)
        ]
    )

    report = {
        "truth": truth.as_dict(),
        "recovered": recovered.as_dict(),
        "reference_radius": reference_radius,
        "profile_scale": args.scale,
        "noise_normalisation": args.noise_normalisation,
        "peak_capture_probability": scale,
        "saturation_index": {
            "truth": args.saturation_index,
            "recovered": recovered_index,
            "on_grid_edge": on_edge,
            "profile_loss": profile.tolist(),
            "interval_68": list(interval_68),
            "interval_95": list(interval_95),
            "width_in_grid_steps_95": steps_95,
            "residual_variance": variance,
            "residuals": n_residuals,
        },
        "grid": {
            "capture_radius": radii.tolist(),
            "ssdna_persistence": persistences.tolist(),
            "saturation_index": indices.tolist(),
        },
        "n_architectures": len(contexts),
        "loss": result.loss,
        "noise_sigma": args.noise,
        "mode_offsets": offsets.tolist(),
        "mode_exact": int(np.count_nonzero(offsets == 0)),
        "mode_within_one": int(np.count_nonzero(np.abs(offsets) <= 1)),
    }

    print(f"reference radius           {reference_radius:.1f} A")
    print(f"profile scale              {args.scale}")
    print(f"noise normalisation        {args.noise_normalisation}")
    print(f"peak capture probability   {scale:.5f}")
    print()
    print("parameter            true      recovered")
    print(f"{'capture_radius':18s} {truth.capture_radius:8.3f}  {recovered.capture_radius:8.3f}")
    print(
        f"{'ssdna_persistence':18s} {truth.ssdna_persistence:8.3f}  "
        f"{recovered.ssdna_persistence:8.3f}"
    )
    print(f"{'saturation_index':18s} {args.saturation_index:8.3f}  {recovered_index:8.3f}")
    print()
    print(
        f"saturation index within 68 per cent  [{interval_68[0]:.3f}, {interval_68[1]:.3f}]"
    )
    print(
        f"saturation index within 95 per cent  [{interval_95[0]:.3f}, {interval_95[1]:.3f}]"
        f"   {steps_95:.1f} grid steps wide"
    )
    if on_edge:
        print("the link sits on a grid edge, so these profiles do not identify it")
    print()
    print(f"architectures      {report['n_architectures']}")
    print(
        f"modes recovered    {report['mode_exact']} exact, "
        f"{report['mode_within_one']} within 1 nt"
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2)
        handle.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
